FROM node:13-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install
COPY . /app
RUN yarn build
RUN mkdir -p /workspace && (rm -rf /workspace/_static || true) && mv public /workspace/_static
